# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
# title:            Hyde
# tagline:          'A Jekyll theme'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'

#
name:             'Phil'
author:           'Phil'
url:              https://philparadis.github.io
baseurl:          /

# Paginate
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/philparadis/philparadis.github.io.git

# Theme
# theme: jekyll-theme-hyde
# Name of your site (displayed in the header)
# Short bio or description (displayed in the header)
description: "Blog and project page for IFT6266-H2017"
# URL of your avatar or profile pic
avatar: "/assets/my-photo-2017.jpg"
# Time zone
timezone: "America/New_York"
# Encoding
encoding: "utf-8"

# Those settings willl apply to all pages and posts by default (unless overridden) on my site
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# # Other default values:

# # Where things are
# source:       .
destination:  ./_site
# plugins_dir:  _plugins
layouts_dir:  _layouts
# data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# # Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:   [".git", ".svn"]
# encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# # Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# # Plugins
# whitelist: []
# gems:      []

# # Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  syntax_highlighter: rouge

# # Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname
# show_dir_listing: false

# # Outputting
permalink:     date
paginate_path: /page:num
# timezone:      null

quiet:    false
verbose:  false
# defaults: []

liquid:
  error_mode: warn

# # Markdown Processors
# rdiscount:
#   extensions: []

# redcarpet:
#   extensions: []

# kramdown:
#   auto_ids:       true
#   entity_output:  as_char
#   toc_levels:     1..6
#   smart_quotes:   lsquo,rsquo,ldquo,rdquo
#   input:          GFM
#   hard_wrap:      false
#   footnote_nr:    1

